################################################################################
#                      Alacritty TOML configuration file                       #
#                                                                              #
# Documentation for this configuration file can be found in `man 5 alacritty`  #
################################################################################

shell = "/bin/zsh"
live_config_reload = true

[window]
opacity = 0.95
decorations_theme_variant = "Dark"

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 10.0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }
blink_timeout = 0
blink_interval = 250

[mouse]
hide_when_typing = true
